from __future__ import annotations

import os
import uuid
from typing import Any

from fastapi import APIRouter, HTTPException, Query, Request

from app.dependencies import get_services
from app.schemas import AgentTurnRequest, AgentTurnResponse, RAGSearchRequest, ToolInvokeRequest
from app.services.agent import TierZeroAgent
from app.services.gemini_agent import GeminiAgenticEngine
from app.services.ingestion import build_rag
from app.services.trace import TraceRecorder
from app.tools.registry import ToolRegistry


router = APIRouter()


@router.get("/health")
def health() -> dict[str, Any]:
    services = get_services()
    rag_stats = services.rag.stats()
    kb_ready = rag_stats.get("documents", 0) > 0
    return {
        "status": "ok",
        "service": "agrisense-tier0-sandbox",
        "agent_service_healthy": True,
        "sandbox_service_healthy": True,
        "kb_ready": kb_ready,
        "external_weather_mode_enabled": services.settings.external_mode,
        "environment": services.settings.app_env,
        "external_mode": services.settings.external_mode,
        "llm_provider": services.settings.llm_provider,
        "gemini_configured": bool(services.settings.gemini_api_key or os.environ.get("GEMINI_API_KEY")),
        "geoapify_configured": bool(services.settings.geoapify_api_key),
        "rag": rag_stats,
    }


@router.post("/v1/agent/turn", response_model=AgentTurnResponse)
async def agent_turn(payload: AgentTurnRequest) -> AgentTurnResponse:
    agent = TierZeroAgent(get_services())
    try:
        return await agent.turn(payload)
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"type": type(exc).__name__, "message": str(exc)}) from exc


@router.post("/v1/agent/agentic-turn", response_model=AgentTurnResponse)
async def agentic_turn(payload: AgentTurnRequest) -> AgentTurnResponse:
    engine = GeminiAgenticEngine(get_services())
    try:
        return await engine.run_turn(payload)
    except Exception as exc:
        raise HTTPException(status_code=500, detail={"type": type(exc).__name__, "message": str(exc)}) from exc


@router.get("/v1/tools/catalog")
def tool_catalog() -> dict[str, Any]:
    registry = ToolRegistry(get_services())
    return {
        "format": "OpenAI-compatible function tool definitions",
        "tools": registry.catalog,
        "note": "The deterministic /v1/agent/turn route already enforces the Tier-0 state machine; this catalog is for an external LLM runtime.",
    }


@router.post("/v1/tools/invoke")
async def invoke_tool(payload: ToolInvokeRequest) -> dict[str, Any]:
    services = get_services()
    session_id = services.database.ensure_session(payload.session_id)
    trace = TraceRecorder(services.database, session_id)
    registry = ToolRegistry(services)
    try:
        result = await trace.call(
            payload.name,
            payload.arguments,
            lambda: registry.invoke(payload.name, payload.arguments),
            source_kind="direct_tool_invocation",
        )
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except (ValueError, TypeError) as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return {
        "session_id": session_id,
        "trace_id": trace.trace_id,
        "tool": payload.name,
        "result": result,
        "trace": services.database.get_trace(session_id, trace.trace_id),
    }


@router.post("/v1/rag/search")
def rag_search(payload: RAGSearchRequest) -> dict[str, Any]:
    services = get_services()
    results = services.rag.search(
        payload.query,
        top_k=payload.top_k,
        crop_id=payload.crop_id,
        district=payload.district,
        upazila=payload.upazila,
        source_kind=payload.source_kind,
        include_mock=payload.include_mock,
    )
    return {"query": payload.query, "results": [item.model_dump(mode="json") for item in results]}


@router.get("/v1/kb/stats")
def kb_stats() -> dict[str, Any]:
    services = get_services()
    stats = services.rag.stats()
    stats["supported_planning_crops"] = [
        {"crop_id": crop_id, "crop_name": services.kb.crop_name(crop_id)}
        for crop_id in services.kb.supported_crop_ids
    ]
    stats["data_policy"] = {
        "provided_source_derived": "Bangladesh agronomic and suitability records supplied by the user.",
        "provided_mock": "Synthetic crop planning and economics pack supplied by the user.",
        "generated_mock_gap": "Synthetic missing fields generated by this sandbox and always tagged mock.",
        "live_external": "Geoapify geocoding and Open-Meteo weather when configured/available.",
    }
    stats["evidence_classification"] = {
        "real_or_reviewed": [
            "farmer-provided farm facts",
            "geocoding provider result",
            "live weather values",
            "reviewed crop suitability evidence",
            "reviewed crop-calendar guidance",
            "reviewed fertilizer timing/guardrail evidence",
        ],
        "seeded_demonstration_assumptions": [
            "exact fertilizer quantities where not backed by a soil test or AEZ-specific table",
            "expected yield",
            "input prices",
            "crop selling price",
            "pest-prevention cost",
            "some irrigation cost values",
        ],
        "calculated_by_code": [
            "suitability components",
            "total cost",
            "expected revenue",
            "net profit",
            "ROI",
            "break-even price",
            "break-even yield",
            "scenario deltas",
            "validation status",
        ],
        "judge_statement": "AgriSense never promotes seeded demonstration assumptions into public evidence. Every output carries a classification so the farmer and judge can see its authority.",
    }
    return stats


@router.get("/v1/sessions/{session_id}")
def get_session(session_id: str) -> dict[str, Any]:
    services = get_services()
    session = services.database.get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    session["messages"] = services.database.list_messages(session_id)
    return session


@router.get("/v1/sessions/{session_id}/trace")
def get_session_trace(
    session_id: str, trace_id: str | None = Query(default=None)
) -> dict[str, Any]:
    services = get_services()
    if not services.database.get_session(session_id):
        raise HTTPException(status_code=404, detail="Session not found")
    return {"session_id": session_id, "trace_id": trace_id, "trace": services.database.get_trace(session_id, trace_id)}


@router.delete("/v1/sessions/{session_id}")
def delete_session(session_id: str) -> dict[str, Any]:
    deleted = get_services().database.delete_session(session_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Session not found")
    return {"deleted": True, "session_id": session_id}


@router.post("/v1/admin/rebuild-rag")
def rebuild_rag() -> dict[str, Any]:
    services = get_services()
    if not services.settings.allow_admin_rebuild:
        raise HTTPException(status_code=403, detail="Set ALLOW_ADMIN_REBUILD=true to enable this endpoint")
    result = build_rag(services.settings, force=True)
    get_services.cache_clear()
    return result
